# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pdfwizard.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, 
    QMetaObject, QRect, Qt)
from PySide6.QtGui import (QCursor,
    QFont)
from PySide6.QtWidgets import (QComboBox, QHBoxLayout, QLabel,
    QLineEdit, QPushButton, QSizePolicy,
    QSpacerItem, QStackedWidget, QStatusBar, QTextEdit,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(820, 663)
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(9, 9, 118, 601))
        self.widget.setStyleSheet(u"QWidget{\n"
"background-color:rgb(47, 149, 239)\n"
"}\n"
"QLabel{\n"
"background-color:white;\n"
"color:blue;\n"
"}\n"
"\n"
"QPushButton{\n"
"color:white;\n"
"height:22px;\n"
"border:none;\n"
"padding-left:5px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: #F5FAFE;\n"
"color:#2F95EF;\n"
"font-weight:bold\n"
"}")
        self.verticalLayout = QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(-1, -1, 9, -1)
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        font1 = QFont()
        font1.setFamilies([u"Times New Roman"])
        font1.setPointSize(24)
        font1.setWeight(QFont.ExtraBold)
        font1.setItalic(False)
        font1.setUnderline(False)
        self.label.setFont(font1)
        self.label.setAlignment(Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)
        self.label.setMargin(10)
        self.label.setIndent(0)

        self.verticalLayout.addWidget(self.label)

        self.mainconvert_button = QPushButton(self.widget)
        self.mainconvert_button.setObjectName(u"mainconvert_button")
        font2 = QFont()
        font2.setFamilies([u"Times New Roman"])
        font2.setPointSize(14)
        self.mainconvert_button.setFont(font2)
        self.mainconvert_button.setCheckable(True)
        self.mainconvert_button.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.mainconvert_button)

        self.mainextract_button = QPushButton(self.widget)
        self.mainextract_button.setObjectName(u"mainextract_button")
        self.mainextract_button.setFont(font2)
        self.mainextract_button.setCheckable(True)
        self.mainextract_button.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.mainextract_button)

        self.mainsplit_button = QPushButton(self.widget)
        self.mainsplit_button.setObjectName(u"mainsplit_button")
        self.mainsplit_button.setFont(font2)
        self.mainsplit_button.setCheckable(True)
        self.mainsplit_button.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.mainsplit_button)

        self.maininsert_button = QPushButton(self.widget)
        self.maininsert_button.setObjectName(u"maininsert_button")
        self.maininsert_button.setFont(font2)
        self.maininsert_button.setCheckable(True)
        self.maininsert_button.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.maininsert_button)

        self.mainmerge_button = QPushButton(self.widget)
        self.mainmerge_button.setObjectName(u"mainmerge_button")
        self.mainmerge_button.setFont(font2)
        self.mainmerge_button.setCheckable(True)
        self.mainmerge_button.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.mainmerge_button)

        self.mainpassword_button = QPushButton(self.widget)
        self.mainpassword_button.setObjectName(u"mainpassword_button")
        self.mainpassword_button.setFont(font2)
        self.mainpassword_button.setCheckable(True)
        self.mainpassword_button.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.mainpassword_button)

        self.mainwatermark_button = QPushButton(self.widget)
        self.mainwatermark_button.setObjectName(u"mainwatermark_button")
        self.mainwatermark_button.setFont(font2)
        self.mainwatermark_button.setCheckable(True)
        self.mainwatermark_button.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.mainwatermark_button)

        self.mainremove_button = QPushButton(self.widget)
        self.mainremove_button.setObjectName(u"mainremove_button")
        self.mainremove_button.setFont(font2)
        self.mainremove_button.setCheckable(True)
        self.mainremove_button.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.mainremove_button)

        self.verticalSpacer = QSpacerItem(20, 150, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)

        self.pushButton_9 = QPushButton(self.widget)
        self.pushButton_9.setObjectName(u"pushButton_9")
        font3 = QFont()
        font3.setPointSize(14)
        font3.setBold(True)
        self.pushButton_9.setFont(font3)
        self.pushButton_9.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.pushButton_9)

        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(133, 9, 678, 51))
        font4 = QFont()
        font4.setFamilies([u"Vidya"])
        font4.setPointSize(27)
        font4.setBold(True)
        self.label_11.setFont(font4)
        self.label_11.setStyleSheet(u"background-color:rgb(226, 234, 255);\n"
"color:rgb(1, 8, 22);")
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setIndent(0)
        self.main_widget = QWidget(self.centralwidget)
        self.main_widget.setObjectName(u"main_widget")
        self.main_widget.setGeometry(QRect(130, 50, 681, 301))
        self.main_widget.setStyleSheet(u"background-color:rgb(246, 255, 247);\n"
"color: rgb(62, 62, 62);")
        self.widget_7 = QWidget(self.main_widget)
        self.widget_7.setObjectName(u"widget_7")
        self.widget_7.setGeometry(QRect(9, 9, 663, 48))
        self.select_button = QPushButton(self.widget_7)
        self.select_button.setObjectName(u"select_button")
        self.select_button.setGeometry(QRect(-3, 9, 101, 30))
        self.select_button.setFont(font2)
        self.select_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.select_button.setStyleSheet(u"")
        self.select_button.setCheckable(True)
        self.file_path = QLineEdit(self.widget_7)
        self.file_path.setObjectName(u"file_path")
        self.file_path.setGeometry(QRect(104, 14, 211, 19))
        font5 = QFont()
        font5.setFamilies([u"Times New Roman"])
        self.file_path.setFont(font5)
        self.selectfolder_button = QPushButton(self.widget_7)
        self.selectfolder_button.setObjectName(u"selectfolder_button")
        self.selectfolder_button.setGeometry(QRect(325, 9, 109, 30))
        self.selectfolder_button.setFont(font2)
        self.selectfolder_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.selectfolder_button.setCheckable(True)
        self.folder_path = QLineEdit(self.widget_7)
        self.folder_path.setObjectName(u"folder_path")
        self.folder_path.setGeometry(QRect(440, 14, 221, 19))
        self.folder_path.setFont(font5)
        self.widget_6 = QWidget(self.widget_7)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setGeometry(QRect(20, 40, 301, 51))
        self.widget_9 = QWidget(self.main_widget)
        self.widget_9.setObjectName(u"widget_9")
        self.widget_9.setGeometry(QRect(330, 60, 341, 48))
        self.horizontalLayout_3 = QHBoxLayout(self.widget_9)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.output_button = QPushButton(self.widget_9)
        self.output_button.setObjectName(u"output_button")
        self.output_button.setFont(font2)
        self.output_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.output_button.setCheckable(True)
        self.output_button.setAutoExclusive(False)

        self.horizontalLayout_3.addWidget(self.output_button)

        self.output_path = QLineEdit(self.widget_9)
        self.output_path.setObjectName(u"output_path")
        self.output_path.setFont(font5)

        self.horizontalLayout_3.addWidget(self.output_path)

        self.label_6 = QLabel(self.main_widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 140, 121, 22))
        self.label_6.setFont(font2)
        self.show_files = QTextEdit(self.main_widget)
        self.show_files.setObjectName(u"show_files")
        self.show_files.setGeometry(QRect(10, 170, 651, 121))
        font6 = QFont()
        font6.setFamilies([u"Times New Roman"])
        font6.setPointSize(11)
        font6.setItalic(True)
        self.show_files.setFont(font6)
        self.show_files.viewport().setProperty("cursor", QCursor(Qt.SizeFDiagCursor))
        self.show_files.setStyleSheet(u"border: 1px solid")
        self.show_files.setReadOnly(True)
        self.addfiles_button = QPushButton(self.main_widget)
        self.addfiles_button.setObjectName(u"addfiles_button")
        self.addfiles_button.setGeometry(QRect(10, 100, 118, 30))
        self.addfiles_button.setFont(font2)
        self.addfiles_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.addfiles_button.setCheckable(True)
        self.select_document_widget = QWidget(self.main_widget)
        self.select_document_widget.setObjectName(u"select_document_widget")
        self.select_document_widget.setGeometry(QRect(190, 110, 481, 42))
        self.horizontalLayout_4 = QHBoxLayout(self.select_document_widget)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.select_document_insert = QPushButton(self.select_document_widget)
        self.select_document_insert.setObjectName(u"select_document_insert")
        self.select_document_insert.setFont(font2)
        self.select_document_insert.setCursor(QCursor(Qt.PointingHandCursor))
        self.select_document_insert.setCheckable(True)

        self.horizontalLayout_4.addWidget(self.select_document_insert)

        self.insert_document_path = QLineEdit(self.select_document_widget)
        self.insert_document_path.setObjectName(u"insert_document_path")

        self.horizontalLayout_4.addWidget(self.insert_document_path)

        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(130, 350, 681, 261))
        font7 = QFont()
        font7.setFamilies([u"Segoe UI"])
        font7.setPointSize(9)
        font7.setBold(False)
        self.stackedWidget.setFont(font7)
        self.stackedWidget.setStyleSheet(u"background-color:rgb(246, 255, 247);\n"
"color: rgb(62,62,62);")
        self.create_page = QWidget()
        self.create_page.setObjectName(u"create_page")
        self.label_2 = QLabel(self.create_page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(150, 40, 241, 141))
        self.stackedWidget.addWidget(self.create_page)
        self.remove_page = QWidget()
        self.remove_page.setObjectName(u"remove_page")
        self.widget_range_show_remove = QWidget(self.remove_page)
        self.widget_range_show_remove.setObjectName(u"widget_range_show_remove")
        self.widget_range_show_remove.setGeometry(QRect(20, 20, 641, 61))
        self.page_range_remove = QLabel(self.widget_range_show_remove)
        self.page_range_remove.setObjectName(u"page_range_remove")
        self.page_range_remove.setGeometry(QRect(0, 10, 231, 22))
        self.page_range_remove.setFont(font2)
        self.page_range_remove.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.start_page_remove = QLabel(self.widget_range_show_remove)
        self.start_page_remove.setObjectName(u"start_page_remove")
        self.start_page_remove.setGeometry(QRect(218, 10, 91, 22))
        self.start_page_remove.setFont(font2)
        self.start_page_remove.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.start_page_remove.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.start_page_dropdown_remove = QComboBox(self.widget_range_show_remove)
        self.start_page_dropdown_remove.setObjectName(u"start_page_dropdown_remove")
        self.start_page_dropdown_remove.setGeometry(QRect(320, 10, 91, 21))
        self.start_page_dropdown_remove.setCursor(QCursor(Qt.PointingHandCursor))
        self.end_page_remove = QLabel(self.widget_range_show_remove)
        self.end_page_remove.setObjectName(u"end_page_remove")
        self.end_page_remove.setGeometry(QRect(450, 10, 81, 21))
        self.end_page_remove.setFont(font2)
        self.end_page_dropdown_remove = QComboBox(self.widget_range_show_remove)
        self.end_page_dropdown_remove.setObjectName(u"end_page_dropdown_remove")
        self.end_page_dropdown_remove.setGeometry(QRect(530, 10, 91, 22))
        self.remove_button = QPushButton(self.remove_page)
        self.remove_button.setObjectName(u"remove_button")
        self.remove_button.setGeometry(QRect(530, 160, 131, 71))
        font8 = QFont()
        font8.setPointSize(18)
        font8.setBold(True)
        self.remove_button.setFont(font8)
        self.remove_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.remove_button.setStyleSheet(u"background-color:rgb(5, 80, 255);\n"
"color:white;\n"
"border-radius:25px;\n"
"")
        self.remove_button.setCheckable(True)
        self.remove_button.setAutoExclusive(True)
        self.stackedWidget.addWidget(self.remove_page)
        self.split_page = QWidget()
        self.split_page.setObjectName(u"split_page")
        self.split_page.setStyleSheet(u"")
        self.split_button = QPushButton(self.split_page)
        self.split_button.setObjectName(u"split_button")
        self.split_button.setGeometry(QRect(560, 170, 111, 71))
        font9 = QFont()
        font9.setFamilies([u"Times New Roman"])
        font9.setPointSize(18)
        font9.setBold(True)
        self.split_button.setFont(font9)
        self.split_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.split_button.setStyleSheet(u"background-color:rgb(5, 80, 255);\n"
"color:white;\n"
"border-radius:25px;\n"
"")
        self.split_button.setCheckable(True)
        self.split_button.setAutoExclusive(True)
        self.widget_outputfile = QWidget(self.split_page)
        self.widget_outputfile.setObjectName(u"widget_outputfile")
        self.widget_outputfile.setGeometry(QRect(0, 90, 671, 44))
        self.horizontalLayout_6 = QHBoxLayout(self.widget_outputfile)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.label_8 = QLabel(self.widget_outputfile)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setFont(font2)

        self.horizontalLayout_6.addWidget(self.label_8)

        self.output1 = QLineEdit(self.widget_outputfile)
        self.output1.setObjectName(u"output1")
        self.output1.setFont(font2)

        self.horizontalLayout_6.addWidget(self.output1)

        self.label_12 = QLabel(self.widget_outputfile)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setFont(font2)

        self.horizontalLayout_6.addWidget(self.label_12)

        self.output2 = QLineEdit(self.widget_outputfile)
        self.output2.setObjectName(u"output2")
        self.output2.setFont(font2)

        self.horizontalLayout_6.addWidget(self.output2)

        self.widget_range_show = QWidget(self.split_page)
        self.widget_range_show.setObjectName(u"widget_range_show")
        self.widget_range_show.setGeometry(QRect(10, 20, 641, 40))
        self.page_range = QLabel(self.widget_range_show)
        self.page_range.setObjectName(u"page_range")
        self.page_range.setGeometry(QRect(0, 10, 231, 22))
        self.page_range.setFont(font2)
        self.page_range.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.split_at = QLabel(self.widget_range_show)
        self.split_at.setObjectName(u"split_at")
        self.split_at.setGeometry(QRect(420, 10, 59, 22))
        self.split_at.setFont(font2)
        self.split_at.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.split_at.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.page_dropdown = QComboBox(self.widget_range_show)
        self.page_dropdown.setObjectName(u"page_dropdown")
        self.page_dropdown.setGeometry(QRect(490, 10, 91, 21))
        self.page_dropdown.setCursor(QCursor(Qt.PointingHandCursor))
        self.stackedWidget.addWidget(self.split_page)
        self.convert_page = QWidget()
        self.convert_page.setObjectName(u"convert_page")
        self.convert_page.setStyleSheet(u"QPushButton{\n"
"margin:2px bold;\n"
"}")
        self.widget_2 = QWidget(self.convert_page)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(170, 20, 321, 101))
        self.verticalLayout_2 = QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label_5 = QLabel(self.widget_2)
        self.label_5.setObjectName(u"label_5")
        font10 = QFont()
        font10.setPointSize(14)
        self.label_5.setFont(font10)

        self.verticalLayout_2.addWidget(self.label_5)

        self.convert_dropdown = QComboBox(self.widget_2)
        self.convert_dropdown.addItem("")
        self.convert_dropdown.addItem("")
        self.convert_dropdown.addItem("")
        self.convert_dropdown.addItem("")
        self.convert_dropdown.addItem("")
        self.convert_dropdown.setObjectName(u"convert_dropdown")
        font11 = QFont()
        font11.setPointSize(12)
        self.convert_dropdown.setFont(font11)

        self.verticalLayout_2.addWidget(self.convert_dropdown)

        self.convert_button = QPushButton(self.convert_page)
        self.convert_button.setObjectName(u"convert_button")
        self.convert_button.setGeometry(QRect(520, 160, 151, 71))
        self.convert_button.setFont(font8)
        self.convert_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.convert_button.setStyleSheet(u"background-color:rgb(5, 80, 255);\n"
"color:white;\n"
"border-radius:25px;\n"
"")
        self.convert_button.setCheckable(True)
        self.stackedWidget.addWidget(self.convert_page)
        self.merge_page = QWidget()
        self.merge_page.setObjectName(u"merge_page")
        font12 = QFont()
        font12.setFamilies([u"Times New Roman"])
        font12.setPointSize(11)
        self.merge_page.setFont(font12)
        self.merge_button = QPushButton(self.merge_page)
        self.merge_button.setObjectName(u"merge_button")
        self.merge_button.setGeometry(QRect(540, 160, 131, 71))
        self.merge_button.setFont(font9)
        self.merge_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.merge_button.setStyleSheet(u"background-color:rgb(5, 80, 255);\n"
"color:white;\n"
"border-radius:25px;\n"
"")
        self.merge_button.setCheckable(True)
        self.merge_button.setAutoExclusive(True)
        self.stackedWidget.addWidget(self.merge_page)
        self.extract_page = QWidget()
        self.extract_page.setObjectName(u"extract_page")
        self.widget_3 = QWidget(self.extract_page)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(160, 23, 331, 61))
        self.horizontalLayout = QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_3 = QLabel(self.widget_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font2)

        self.horizontalLayout.addWidget(self.label_3)

        self.extract_dropdown = QComboBox(self.widget_3)
        self.extract_dropdown.addItem("")
        self.extract_dropdown.addItem("")
        self.extract_dropdown.setObjectName(u"extract_dropdown")
        self.extract_dropdown.setFont(font2)

        self.horizontalLayout.addWidget(self.extract_dropdown)

        self.extract_button = QPushButton(self.extract_page)
        self.extract_button.setObjectName(u"extract_button")
        self.extract_button.setGeometry(QRect(550, 160, 121, 71))
        self.extract_button.setFont(font9)
        self.extract_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.extract_button.setStyleSheet(u"background-color:rgb(5, 80, 255);\n"
"color:white;\n"
"border-radius:25px;\n"
"")
        self.extract_button.setCheckable(True)
        self.extract_button.setAutoExclusive(True)
        self.stackedWidget.addWidget(self.extract_page)
        self.watermark_page = QWidget()
        self.watermark_page.setObjectName(u"watermark_page")
        self.widget_10 = QWidget(self.watermark_page)
        self.widget_10.setObjectName(u"widget_10")
        self.widget_10.setGeometry(QRect(80, 10, 521, 61))
        self.label_9 = QLabel(self.widget_10)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 30, 131, 16))
        self.label_9.setFont(font2)
        self.watermark_text = QLineEdit(self.widget_10)
        self.watermark_text.setObjectName(u"watermark_text")
        self.watermark_text.setGeometry(QRect(170, 30, 341, 21))
        self.widget_12 = QWidget(self.watermark_page)
        self.widget_12.setObjectName(u"widget_12")
        self.widget_12.setGeometry(QRect(100, 80, 181, 44))
        self.horizontalLayout_5 = QHBoxLayout(self.widget_12)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.label_14 = QLabel(self.widget_12)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setFont(font10)

        self.horizontalLayout_5.addWidget(self.label_14)

        self.watermark_position = QComboBox(self.widget_12)
        self.watermark_position.addItem("")
        self.watermark_position.addItem("")
        self.watermark_position.addItem("")
        self.watermark_position.setObjectName(u"watermark_position")

        self.horizontalLayout_5.addWidget(self.watermark_position)

        self.watermark_button = QPushButton(self.watermark_page)
        self.watermark_button.setObjectName(u"watermark_button")
        self.watermark_button.setGeometry(QRect(530, 160, 131, 81))
        self.watermark_button.setFont(font9)
        self.watermark_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.watermark_button.setStyleSheet(u"background-color:rgb(5, 80, 255);\n"
"color:white;\n"
"border-radius:25px;\n"
"")
        self.watermark_button.setCheckable(True)
        self.watermark_button.setAutoExclusive(True)
        self.stackedWidget.addWidget(self.watermark_page)
        self.protect_page = QWidget()
        self.protect_page.setObjectName(u"protect_page")
        self.widget_4 = QWidget(self.protect_page)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setGeometry(QRect(90, 20, 531, 61))
        self.horizontalLayout_2 = QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label_7 = QLabel(self.widget_4)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setFont(font2)

        self.horizontalLayout_2.addWidget(self.label_7)

        self.password_text = QLineEdit(self.widget_4)
        self.password_text.setObjectName(u"password_text")
        self.password_text.setFont(font2)

        self.horizontalLayout_2.addWidget(self.password_text)

        self.password_button = QPushButton(self.protect_page)
        self.password_button.setObjectName(u"password_button")
        self.password_button.setGeometry(QRect(520, 110, 121, 71))
        self.password_button.setFont(font9)
        self.password_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.password_button.setStyleSheet(u"background-color:rgb(5, 80, 255);\n"
"color:white;\n"
"border-radius:25px;\n"
"")
        self.password_button.setCheckable(True)
        self.password_button.setAutoExclusive(True)
        self.stackedWidget.addWidget(self.protect_page)
        self.insert_page = QWidget()
        self.insert_page.setObjectName(u"insert_page")
        font13 = QFont()
        font13.setPointSize(9)
        font13.setBold(False)
        self.insert_page.setFont(font13)
        self.widget_range_show_2 = QWidget(self.insert_page)
        self.widget_range_show_2.setObjectName(u"widget_range_show_2")
        self.widget_range_show_2.setGeometry(QRect(10, 30, 641, 40))
        self.page_range_insert = QLabel(self.widget_range_show_2)
        self.page_range_insert.setObjectName(u"page_range_insert")
        self.page_range_insert.setGeometry(QRect(0, 10, 231, 22))
        self.page_range_insert.setFont(font2)
        self.page_range_insert.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.insert_at = QLabel(self.widget_range_show_2)
        self.insert_at.setObjectName(u"insert_at")
        self.insert_at.setGeometry(QRect(388, 10, 91, 22))
        self.insert_at.setFont(font2)
        self.insert_at.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.insert_at.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.insert_at_dropdown = QComboBox(self.widget_range_show_2)
        self.insert_at_dropdown.setObjectName(u"insert_at_dropdown")
        self.insert_at_dropdown.setGeometry(QRect(490, 10, 91, 21))
        self.insert_at_dropdown.setCursor(QCursor(Qt.PointingHandCursor))
        self.widget_5 = QWidget(self.insert_page)
        self.widget_5.setObjectName(u"widget_5")
        self.widget_5.setGeometry(QRect(10, 80, 281, 80))
        self.label_4 = QLabel(self.widget_5)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 20, 111, 41))
        self.label_4.setFont(font2)
        self.Insert_options_dropdown = QComboBox(self.widget_5)
        self.Insert_options_dropdown.addItem("")
        self.Insert_options_dropdown.addItem("")
        self.Insert_options_dropdown.addItem("")
        self.Insert_options_dropdown.setObjectName(u"Insert_options_dropdown")
        self.Insert_options_dropdown.setGeometry(QRect(120, 30, 131, 22))
        self.widget_start_end_insert = QWidget(self.insert_page)
        self.widget_start_end_insert.setObjectName(u"widget_start_end_insert")
        self.widget_start_end_insert.setGeometry(QRect(310, 100, 351, 51))
        self.label_10 = QLabel(self.widget_start_end_insert)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 10, 81, 31))
        self.label_10.setFont(font2)
        self.label_13 = QLabel(self.widget_start_end_insert)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(198, 10, 81, 31))
        self.label_13.setFont(font2)
        self.start_page_dropdown = QComboBox(self.widget_start_end_insert)
        self.start_page_dropdown.setObjectName(u"start_page_dropdown")
        self.start_page_dropdown.setGeometry(QRect(110, 10, 68, 22))
        self.end_page_dropdown = QComboBox(self.widget_start_end_insert)
        self.end_page_dropdown.setObjectName(u"end_page_dropdown")
        self.end_page_dropdown.setGeometry(QRect(280, 10, 68, 22))
        self.insert_button = QPushButton(self.insert_page)
        self.insert_button.setObjectName(u"insert_button")
        self.insert_button.setGeometry(QRect(540, 170, 121, 71))
        self.insert_button.setFont(font9)
        self.insert_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.insert_button.setStyleSheet(u"background-color:rgb(5, 80, 255);\n"
"color:white;\n"
"border-radius:25px;\n"
"")
        self.insert_button.setCheckable(True)
        self.insert_button.setAutoExclusive(True)
        self.stackedWidget.addWidget(self.insert_page)
        self.status_label = QLabel(self.centralwidget)
        self.status_label.setObjectName(u"status_label")
        self.status_label.setGeometry(QRect(90, 620, 651, 21))
        font14 = QFont()
        font14.setFamilies([u"Segoe UI"])
        font14.setPointSize(10)
        font14.setBold(False)
        font14.setItalic(False)
        font14.setHintingPreference(QFont.PreferFullHinting)
        self.status_label.setFont(font14)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_9.toggled.connect(MainWindow.close)

        self.stackedWidget.setCurrentIndex(8)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Menu", None))
        self.mainconvert_button.setText(QCoreApplication.translate("MainWindow", u"Convert", None))
        self.mainextract_button.setText(QCoreApplication.translate("MainWindow", u"Extract", None))
        self.mainsplit_button.setText(QCoreApplication.translate("MainWindow", u"Split", None))
        self.maininsert_button.setText(QCoreApplication.translate("MainWindow", u"Insert", None))
        self.mainmerge_button.setText(QCoreApplication.translate("MainWindow", u"Merge", None))
        self.mainpassword_button.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.mainwatermark_button.setText(QCoreApplication.translate("MainWindow", u"Watermark", None))
        self.mainremove_button.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#000050;\">Welcome To PDF Wizard</span></p></body></html>", None))
        self.select_button.setText(QCoreApplication.translate("MainWindow", u"Select File", None))
        self.selectfolder_button.setText(QCoreApplication.translate("MainWindow", u"Select Folder", None))
        self.output_button.setText(QCoreApplication.translate("MainWindow", u"Output Folder", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Added Files:", None))
        self.show_files.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Added files will be displayed here", None))
        self.addfiles_button.setText(QCoreApplication.translate("MainWindow", u"Add File/Files", None))
        self.select_document_insert.setText(QCoreApplication.translate("MainWindow", u"Select Document", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Create Page", None))
        self.page_range_remove.setText(QCoreApplication.translate("MainWindow", u"Page Range: ", None))
        self.start_page_remove.setText(QCoreApplication.translate("MainWindow", u"Start Page", None))
        self.end_page_remove.setText(QCoreApplication.translate("MainWindow", u"End Page", None))
        self.remove_button.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.split_button.setText(QCoreApplication.translate("MainWindow", u"Split", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Save as", None))
        self.output1.setText(QCoreApplication.translate("MainWindow", u"output_pdf1", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"and", None))
        self.output2.setText(QCoreApplication.translate("MainWindow", u"output_pdf2", None))
        self.page_range.setText(QCoreApplication.translate("MainWindow", u"Page Range: ", None))
        self.split_at.setText(QCoreApplication.translate("MainWindow", u"Split At", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Convert from:", None))
        self.convert_dropdown.setItemText(0, QCoreApplication.translate("MainWindow", u"Doc/Docx to PDF", None))
        self.convert_dropdown.setItemText(1, QCoreApplication.translate("MainWindow", u"Image to PDF", None))
        self.convert_dropdown.setItemText(2, QCoreApplication.translate("MainWindow", u"Pdf to Image(.jpg)", None))
        self.convert_dropdown.setItemText(3, QCoreApplication.translate("MainWindow", u"Pdf to Image(.jpeg)", None))
        self.convert_dropdown.setItemText(4, QCoreApplication.translate("MainWindow", u"Pdf to Image(.png)", None))

        self.convert_button.setText(QCoreApplication.translate("MainWindow", u"Convert", None))
        self.merge_button.setText(QCoreApplication.translate("MainWindow", u"Merge", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Extract Text/Images", None))
        self.extract_dropdown.setItemText(0, QCoreApplication.translate("MainWindow", u"Text", None))
        self.extract_dropdown.setItemText(1, QCoreApplication.translate("MainWindow", u"Images", None))

        self.extract_button.setText(QCoreApplication.translate("MainWindow", u"Extract", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Watermark Text", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Position", None))
        self.watermark_position.setItemText(0, QCoreApplication.translate("MainWindow", u"Top", None))
        self.watermark_position.setItemText(1, QCoreApplication.translate("MainWindow", u"Center", None))
        self.watermark_position.setItemText(2, QCoreApplication.translate("MainWindow", u"Bottom", None))

        self.watermark_button.setText(QCoreApplication.translate("MainWindow", u"Watermark", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Type Your Password", None))
        self.password_button.setText(QCoreApplication.translate("MainWindow", u"Encrypt", None))
        self.page_range_insert.setText(QCoreApplication.translate("MainWindow", u"Page Range: ", None))
        self.insert_at.setText(QCoreApplication.translate("MainWindow", u"Insert At", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Insert Options", None))
        self.Insert_options_dropdown.setItemText(0, QCoreApplication.translate("MainWindow", u"Page Range", None))
        self.Insert_options_dropdown.setItemText(1, QCoreApplication.translate("MainWindow", u"Whole Document", None))
        self.Insert_options_dropdown.setItemText(2, QCoreApplication.translate("MainWindow", u"Single Page", None))

        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Start Page", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"End Page", None))
        self.insert_button.setText(QCoreApplication.translate("MainWindow", u"Insert", None))
        self.status_label.setText(QCoreApplication.translate("MainWindow", u"                Application developed by Arunava Kar             Leave a message at arunavakaronly@gmail.com", None))
    # retranslateUi

